<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container23vhzxi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container23vhzxi/appProdProjectContainer.php') {
    touch(__DIR__.'/Container23vhzxi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container23vhzxi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container23vhzxi\appProdProjectContainer([
    'container.build_hash' => '23vhzxi',
    'container.build_id' => 'dd686f30',
    'container.build_time' => 1593675226,
], __DIR__.\DIRECTORY_SEPARATOR.'Container23vhzxi');
