<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3sjxwsf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3sjxwsf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3sjxwsf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3sjxwsf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3sjxwsf\appDevDebugProjectContainer([
    'container.build_hash' => '3sjxwsf',
    'container.build_id' => '0154f373',
    'container.build_time' => 1594309210,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3sjxwsf');
